resource_types:
- name: pull-request
  type: registry-image
  source:
    repository: teliaoss/github-pr-resource
- name: slack-notification
  type: registry-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: pull-request
  type: pull-request
  check_every: 1h
  webhook_token: ((github-webhook-token))
  source:
    repository: OdekoTeam/CHANGE_TO_REPOSITORY_NAME
    access_token: ((git-release-token))
- name: concourse
  type: git
  check_every: 1h
  source:
    branch: master
    password: ((git-release-token))
    uri: https://github.com/OdekoTeam/concourse.git
    username: ((git-user))
- name: concourse-image-ruby
  type: registry-image
  source:
    repository: docker.odeko.com/odeko/concourse-rails-base
    tag: 2.7.4-node-16
- name: slack-alert
  type: slack-notification
  source:
    url: ((slack-build-webhook-token))

jobs:
- name: test
  plan:
  - in_parallel:
    - get: pull-request
      trigger: true
      version: every
      params:
        submodules: true
      attempts: 3
    - get: concourse
      attempts: 3
    - get: concourse-image-ruby
      attempts: 3
  - in_parallel:
    - put: update-pr-status
      params:
        path: pull-request
        status: pending
      get_params:
        skip_download: true
      resource: pull-request
      attempts: 3
    - task: install
      input_mapping:
        repo: pull-request
      image: concourse-image-ruby
      file: concourse/tasks/rails/test/install.yml
      params:
        GITHUB_SSH_KEY: "((git-ssh-private-key))"
      attempts: 3
  - in_parallel:
    - task: test
      input_mapping:
        repo: pull-request
      image: concourse-image-ruby
      file: concourse/tasks/rails/test/test-nodeps.yml
      vars:
        additional_databases: ''
      attempts: 3
    - task: lint
      input_mapping:
        repo: pull-request
      image: concourse-image-ruby
      file: concourse/tasks/rails/test/lint.yml
      attempts: 3
  on_failure:
    do:
    - in_parallel:
      - put: update-pr-status
        params:
          path: pull-request
          status: failure
        get_params:
          skip_download: true
        resource: pull-request
        attempts: 3
      - task: slack-message
        file: concourse/tasks/common/slack_pr_message.yml
        attempts: 3
    - put: slack-alert
      params:
        username: 'concourse'
        icon_url: https://concourse-ci.org/images/trademarks/concourse-black.png
        text_file: slack-message/slack-info
        text: |
          :red_circle: *<https://concourse.odeko.com/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}|${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}> failed*
          $TEXT_FILE_CONTENT
        silent: true
      attempts: 3
  on_success:
    do:
    - in_parallel:
      - put: update-pr-status
        params:
          path: pull-request
          status: success
        get_params:
          skip_download: true
        resource: pull-request
        attempts: 3
      - task: slack-message
        file: concourse/tasks/common/slack_pr_message.yml
        attempts: 3
    - put: slack-alert
      params:
        username: 'concourse'
        icon_url: https://concourse-ci.org/images/trademarks/concourse-black.png
        text_file: slack-message/slack-info
        text: |
          :thumbsup: *<https://concourse.odeko.com/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}|${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}> succeeded*
          $TEXT_FILE_CONTENT
        silent: true
      attempts: 3
